name: Resume CI
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install texlive
        run: sudo apt install texlive-base 
      - name: Install texlive-latex-extra
        run: sudo apt-get install texlive-latex-extra
      - name: Build pdf
        run: pdflatex -output-directory output resume.tex 
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with: 
          commit-message: resume build
          branch: latest_resume
          title: '[CI] pdflatex build'